version: "3.9"

services:
  frontend:
    build: ./app/frontend
    ports:
      - 3030:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3030"]  # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 10s
      retries: 5
  backend:
    build: ./app/backend
    ports:
      - 3031:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_URL=
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3031"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
  database:
    image: mysql:8.0.21
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores